# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# build matrix; turn on vdiffr only on r release
matrix:
  include:
  - r: devel
    # avoind errors due to world clock API (hopefully can be removed in future)
    env: _R_CHECK_SYSTEM_CLOCK_=false
  - r: release
    env: VDIFFR_RUN_TESTS=true
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
  
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

# environment variables set for all builds
env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false

after_success:
  - Rscript -e 'covr::codecov()'
