---
title: "Introduction to dtwarppers"
author: "David Shilane, Caffrey Lee, Zoe Huang, Anderson Nelson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to dtwarppers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}

library(knitr)
opts_chunk$set(echo = F, comment="", warning = FALSE, message = FALSE, collapse = T, tidy.opts=list(width.cutoff=60), tidy = TRUE, comment = '#>')

```

```{r libraries}

#library(DTwrapers)
library(formulaic)
library(data.table)
data("snack.dat", package = "formulaic")

```

```{r constants}

id.name <- "User ID"
awareness.name <- "Awareness"
satisfaction.name <- "Satisfaction"
age.name <- "Age"
gender.name <- "Gender"
income.name <- "Income"
region.name <- "Region"
persona.name <- "Persona"
bp.patterns <- "BP_"
consumption.name <- "Consumption"
consideration.name <- "Consideration"
advocacy.name <- "Advocacy"
satisfaction.name <- "Satisfaction"
age.group.name <- "Age Group"
income.group.name <- "Income Group"

```

# Introduction 



